CREATE DATABASE CardMusical;
USE CardMusical;

CREATE TABLE Musicas 
(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(50) NOT NULL,
    genero VARCHAR(1) NOT NULL,
    artista VARCHAR(50) NOT NULL,
    imagem VARCHAR(255) NOT NULL,
    corCard VARCHAR(1) NOT NULL,
    linkMusica VARCHAR(255) NOT NULL,
);
